name: 'docker-image-test'

#on:
#  push

jobs:
  docker-image-test:
    runs-on: ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: Install docker
      run: |
        apt update 
        apt install -y ca-certificates curl gnupg
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg

        echo \
        "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
        tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt update 

        apt install -y docker-ce

        curl -o /usr/local/bin/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe



    - name: Build the Docker image
      run: docker build . --file Dockerfile.test --tag consoleapp1-build-image:latest